### ISSUE TITLE
Error for IDs

### ISSUE THREAD

**Issue by silectobi4** [David20122/Sound-Space-Quantum-Editor#6]
So i was making a map it worked after i redownloaded the editor BUT now i cant do another song 1 song worked the second song doesnt wanna work like it gives me a error
<img width="829" alt="E" src="https://user-images.githubusercontent.com/76253019/102712279-30835700-42c0-11eb-8d67-c33695dcf79f.PNG">
r

**Comment by silectobi4** [comment]
**E i know legit nothing about this scripting stuff**

**Comment by Avibah** [comment]
that error shows up when the editor cant access the audio associated with that id, which could mean you cant access roblox's servers or you have an outdated version of the editor and will need the latest version

if you have the latest version already then either the roblox servers are down near you or the editor is unable to contact them, either because of a firewall setting or internet issues

the reason one id works and not another is because the first is cached so it doesnt need to contact any servers to load the cached audio

**Comment by Uncle0698** [comment]
When Error 403 occured, 90% of the time the audio ID was archived so the game and the editor couldn't even play the audio.

See example: 4445168332, 4641686730
They will also show like [this](https://i.imgur.com/ES3wX2y.png).
